### ISSUE TITLE
[Proposal] <Search>

### ISSUE THREAD

**Issue by AbhJ** [felvin-search/instant-apps#81]
# Summary
When the user is searching outside the box (some app that is not available), the user should be returned a standard search about the text input rather than about "Hello"
![Screenshot from 2021-09-07 20-36-18](https://user-images.githubusercontent.com/48042655/132368124-3ddd1d91-4dac-40b3-9194-c893ff75a57c.png)

**Comment by sahil-shubham** [comment]
Thank you for your interest in felvin search. This repository is meant for development of instant apps, hence it's not going to show search results for queries. We show the search results for "hello" so that one can judge how it would is a real environment. 

To search and use the instant apps, use [felvin.com](https://felvin.com). Also, go through README to realize how everything fits together, and read CONTRIBUTING if you are interested in contributing. 

Closing this issue. And also "Life isn't sad".

**Comment by OrkoHunter** [comment]
@sahil-shubham @hargup I think we can modify the test results data so that they don't cause this confusion. The results themselves could say that felvin.com is where the actual search is supposed to happen. 

Or a big banner on top 😅

**Comment by sahil-shubham** [comment]
I am making an issue regarding explicitly showing that this is a sandbox environment, would think of a interesting way of showing it because simply writing it can go unnoticed.
